steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "docker"
    args:
      [
        "buildx",
        "build",
        "--platform",
        "linux/amd64",
        "-t",
        "us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/olympic-coast-treks:$COMMIT_SHA",
        "--push",
        ".",
      ]

timeout: "1200s"
