name: Deploy Frontend to Firebase Hosting

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  NODE_VERSION: "22"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build project
        run: |
          cd frontend
          npm run build

      - name: Debug Authentication Flow
        run: |
          echo "=== Step 1: Check WIF Authentication ==="
          echo "Credentials file path: ${{ steps.auth.outputs.credentials_file_path }}"
          echo "Service Account: ${{ secrets.WIF_SERVICE_ACCOUNT }}"
          echo "Project ID: ${{ secrets.FIREBASE_PROJECT_ID }}"

          echo "=== Step 2: Check gcloud auth ==="
          gcloud auth list --format="table(account,status)"
          gcloud config get-value account

          echo "=== Step 3: Test Google Cloud access ==="
          gcloud projects describe ${{ secrets.FIREBASE_PROJECT_ID }} || echo "Failed to access project via gcloud"

          echo "=== Step 4: Test Firebase CLI authentication ==="
          cd frontend
          export GOOGLE_APPLICATION_CREDENTIALS="${{ steps.auth.outputs.credentials_file_path }}"

          echo "Credentials file exists: $(test -f "$GOOGLE_APPLICATION_CREDENTIALS" && echo 'YES' || echo 'NO')"

          # Try to authenticate Firebase CLI
          npx firebase-tools@latest login:ci --token "$(gcloud auth print-access-token)" || echo "Firebase login failed"

          echo "=== Step 5: List all Firebase projects (should show your project) ==="
          npx firebase-tools@latest projects:list || echo "Cannot list Firebase projects"

          echo "=== Step 6: Try to access specific project ==="
          npx firebase-tools@latest use ${{ secrets.FIREBASE_PROJECT_ID }} || echo "Cannot access specific project"
